[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "A59NWes8W8oBKHt2zKaU8TN6nra3vn1XEn4x1PYr3CF1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/codespace/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
