[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "EcFhg4MrQY5QNFs3H1VAPy9JhLFARFrLJoDeKfUsUSAi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/codespace/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
